# Auto-generated by asn1ate v.0.6.0 from ents.asn1
# (last modified on 2019-08-26 06:38:29.656412)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class ListValues(univ.SequenceOf):
    pass


ListValues.componentType = char.UTF8String()


class Value(univ.Choice):
    pass


Value.componentType = namedtype.NamedTypes(
    namedtype.NamedType('strVal', char.UTF8String()),
    namedtype.NamedType('listVal', ListValues()),
    namedtype.NamedType('boolVal', univ.Boolean())
)


class Entitlement(univ.Sequence):
    pass


Entitlement.componentType = namedtype.NamedTypes(
    namedtype.NamedType('key', char.UTF8String()),
    namedtype.NamedType('val', Value())
)


class Ents(univ.SetOf):
    pass


Ents.componentType = Entitlement()


